/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assign2;

public class Store {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Store().getGreeting());
    }
}
